### ISSUE TITLE
Duplicated words

### ISSUE THREAD

**Issue by lsolano** [SquareBracketAssociates/LearningOOPWithPharo#17]
**Found some repeated words in first chapters**

1. `~\Chapters\Introduction\Introduction.pillar` (is)
       ". This is ~~is~~ what I do frequently during my coding"

2. `~\Chapters\GettingStarted\GettingStarted.pillar` (and)
       "There are many loops and ~~and~~ conditional in Pharo"

**Comment by jecisc** [comment]
Thank you. I'll do the changes later this week end if no one do it before.

**Comment by Ducasse** [comment]
Tx you!

**Comment by lsolano** [comment]
You're welcome.
