### ISSUE TITLE
A minor typo in chapter 14 Inheritance: Incremental definition and behavior reuse

### ISSUE THREAD

**Issue by ramix** [SquareBracketAssociates/LearningOOPWithPharo#25]
This following typo (tagged with $$$) is located in the introduction:

In this chapter we present the fundamental concept of inheritance that al-
lows a class to reuse and extend the behavior of another class. The idea is
that as a programmer we do not want to rewrite from scratch a functionality
if another class already offers it. A $$$ programm $$$ specialises the implemented
behavior into the new behavior he wants. Inheritance lets us express this
concept specialisation. Using inheritance we create trees of concepts where
more precise ones refine more abstract and generic ones.

**Comment by SergeStinckwich** [comment]
Thank you René for your typo modifications, but maybe you can propose direct modification (PR) so it will be easier to integrate.

**Comment by Ducasse** [comment]
Oh yes!
