### ISSUE TITLE
Question : What schould be the output of the add: countsofValue be 

### ISSUE THREAD

**Issue by RoelofWobben** [SquareBracketAssociates/LearningOOPWithPharo#37]
Hello Stepharo, 

In the Wallet chapter I have to make a function `#add: countsofValue" .

Should the output of that function  be : ` #(0,2, 0,2,0,2, 0,5) `   
or should it be  ` #(3 -> 0.2, 1 -> 0.5) ` 

this is not clear from the book 

Regards, 

Roelof

**Comment by Ducasse** [comment]
Thanks I will have a look later.
In any case it cannot be neither of them because , does not work in arrays

**Comment by Ducasse** [comment]
You should read the test. It shows a clear example of the API


WalletTest >> testCanPay
	| w |
	w := Wallet new.
	w add: 2 coinsOfValue: 0.50.
	w add: 3 coinsOfValue: 0.20.
	w add: 1 coinsOfValue: 0.02.
	w add: 5 coinsOfValue: 0.05.
	self assert: (w canPay: 2) not.
	self assert: (w canPay: 0.50)


I'm sorry but I cannot do more than what I wrote

Now define the method ==add: anInteger coinsOfValue: aNumber==. Browse the class ==Bag== to find the messages that you can send to a bag.


[[[	
Wallet >> add: anInteger coinsOfValue: aNumber
	"Add to the receiver, anInteger times a coin of value aNumber"
	
	... Your solution ...
]]]
