### ISSUE TITLE
Test fails on printOn 

### ISSUE THREAD

**Issue by RoelofWobben** [SquareBracketAssociates/LearningOOPWithPharo#40]
you defined printOn on the ENegation classs as : 

```
ENegation >> printOn: aStream
aStream nextPutAll: '- '
aStream nextPutAll: expression printString
```

and negated as : 

``` 
negated
	^ expression
```

but then this test is failing : 

```
testPrinting
	self assert: (EConstant value: 5) negated printString equals: '-5'
``` 

the outcome willl be  -  5  instead of -5.

Or did I do something wrong ?

Roelof

**Comment by Ducasse** [comment]
this is mistake

**Comment by Ducasse** [comment]
When you report a problem can you mention the page and the chapter?

**Comment by Ducasse** [comment]
I could not find the corresponding testPrinting in the pdf

**Comment by RoelofWobben** [comment]
sorry the name is my fault

it is this test 

``` 
ENegationTest >> testEvaluateWithClassCreationMessage
self assert: (ENegation expression: (EConstant value: 5)) evaluate
equals: -5
```

page 182 chapter 16.9

**Comment by RoelofWobben** [comment]
very wierd 

now I have the code from the book and changed it to use evulateWith  the test is green 

```
testEvaluateWithClassCreationMessage
	self
		assert:
			((ENegation expression: (EConstant value: 5))
				evaluateWith: Dictionary new)
		equals: -5
```

this one works fine

**Comment by Ducasse** [comment]
this is normal because this is not a printstring but the test checks the value
