### ISSUE TITLE
Wallet chapter 11.2  missing CoinNumbers

### ISSUE THREAD

**Issue by ghost** [SquareBracketAssociates/LearningOOPWithPharo#41]
Hello, 

The test is talking about coinNumbers.
```
WalletTest >> testCoins
| w |
w := Wallet new.
w add: 2 coinsOfValue: 0.50.
w add: 3 coinsOfValue: 0.20.
self assert: w coinNumber = 5
```

but never in this chapter the function is explained or is told to the user to make it on thier own. 

where on 11.4 page 112 the rest is explained. 

Maybe forgotten ? 

Regards, 

Roelof

**Comment by Ducasse** [comment]
"The test adds several coins of different values and verifies that we did not lose any coins."
I added a sentence about the method add: coinsOfValue:

**Comment by RoelofWobben** [comment]
yes, that is correct
the add function is mentioned and  made later
but the im talking about the function #coinNumber and except the test there is no mention about whatit schuld do. 

Roe;lof
