### ISSUE TITLE
Typo in Chapter 3 page 22 (mater rev: b7eb254)

### ISSUE THREAD

**Issue by offray** [SquareBracketAssociates/LearningOOPWithPharo#44]
It says:

```Smalltalk
'Pharo' allButFirst: 2==
>>> 'aro'
```

It should be:

```Smalltalk
'Pharo' allButFirst: 2
>>> 'aro'
```

And

```Smalltalk
3 to: 10 by: 2
>>> (3 to: 10 by: 2)
```
should be:

```Smalltalk
3 to: 10 by: 2
>>> #(3 5 7 9)
```
(I don't know if the syntax for intervals is the same that for arrays).

**Comment by Ducasse** [comment]
Thanks I will fix it.

**Comment by Ducasse** [comment]
On the pdf I have

A keyword message can take one or more arguments that are inserted in the message name.
'Pharo' allButFirst: 2
>>> 'aro'
3 to: 10 by: 2
>>> (3 to: 10 by: 2)

so may be it was already fixed

**Comment by Ducasse** [comment]
Is it on a printed version? or on pdf. 
I should probably update the pdf (the commit version you mention is from may 2018 and I did a lot of work since then).

**Comment by offray** [comment]
It is on the PDF.

**Comment by Ducasse** [comment]
Thanks I will change the pdf to use the latest version. Probably the web site is using an old one.
