### ISSUE TITLE
Palindrome as Exercise

### ISSUE THREAD

**Issue by rcpacheco** [SquareBracketAssociates/LearningOOPWithPharo#7]
I think it may be good idea to include the solution to this excercise, maybe at the end of the book, just for completeness.

I came up with two possible solutions, but I'n not sure wich one would be more suited to the language; the first one was based on the clues in the text. The second was based on some code you commented out in the chapter:

String >> isPalindrome
|res ser |
res := OrderedCollection new.
ser := OrderedCollection new.
self do: [ :aChar | Character space = aChar ifFalse: [ res add: aChar asLowercase. ser addFirst: aChar asLowercase] ].
res with: ser do: [ :f :s | (f = s) ifFalse: [ ^ false] ].
^ true

String >> isPalindrome2
|word|
word := self asLowercase reject: [ :aChar | aChar = Character space].
1 to: word size do: [:i | (word at: i) = (word at: word size + 1 - i) ifFalse: [^ false]].
^ true

**Comment by jecisc** [comment]
Maybe you can ask to the mailing list pharo to challenge people to get the best implementation following some criterias as "faster", "more readable", "shorter" implementations.

**Comment by LucFabresse** [comment]
Hello,

And why not this implementation?

String >> isPalindrome
   ^ self reverse = self

#Luc

2017-04-08 21:27 GMT+02:00 CyrilFerlicot <notifications@github.com>:

**Comment by Ducasse** [comment]
You can add the solutions in the solutions file. If not create one. 
About stringKatas I wrote a complete other chapter that compare speed and readbaility and further evolution like does it work with french accents. But I decided not to include it because I was going into bit fiddling and ugly code.

**Comment by rcpacheco** [comment]
Great, I will prepare a file with the code.
